export { default as Navbar } from "./Navbar";
export { default as Sidebar } from "./Sidebar";
export { default as Landing } from "./Landing";
export { default as About } from "./About";
export { default as Projects } from "./Projects";
export { default as Services } from "./Services";
export { default as ServiceCard } from "./ServiceCard";
export { default as Contact } from "./Contact";
export { default as ScrollableLink } from "./ScrollableLink";
